# This is a basic workflow to help you get started with Actions

name: Deploy to Server

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@master

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
  
    - name: Yarn Install
      uses: CultureHQ/actions-yarn@master
      with:
        args: install
    - name: Yarn Install
      uses: CultureHQ/actions-yarn@master
      with:
        args: docs:build
 
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.1
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "docs/.vuepress/dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}

    - name: ssh pipelines
      uses: cross-the-world/ssh-pipeline@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        user: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        connect_timeout: 10s
        script: |
          chown caddy:caddy -R ${{ secrets.REMOTE_TARGET }}
          mkdir /home/krast/test1
